# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1ae5880f8f81f9922c2133f10e78856"
name = "checkout-post-purchase"
application_url = "https://stored-production-update-shaw.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extensibility-victor.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://stored-production-update-shaw.trycloudflare.com/auth/callback",
  "https://stored-production-update-shaw.trycloudflare.com/auth/shopify/callback",
  "https://stored-production-update-shaw.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
